language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - composer selfupdate
  - composer install --prefer-source
  - phpenv rehash

script: 
  - phpunit --coverage-text --coverage-clover=coverage.clover
  - vendor/bin/phpcs --standard=./phpcs.xml -n --report=gitblame ./src
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [[ "$TRAVIS_PHP_VERSION" == "hhvm" ]]; then phpenv global 5.5; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "hhvm-nightly" ]]; then phpenv global 5.5; fi
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - curl -LSs http://box-project.org/installer.php | php
  - php box.phar build
  - if [[ "$TRAVIS_PHP_VERSION" == "hhvm" ]]; then phpenv global hhvm; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "hhvm-nightly" ]]; then phpenv global hhvm-nightly; fi
  - php --version
  - php skeleton.phar --version
